-- ============================================================================
-- Exchange Simulator — Schema (Layer 2)
-- PostgreSQL >= 14
--
-- Run this file first, then 03_seed.sql.
--
-- Design notes:
--   * NUMERIC(20,8) for all monetary / quantity fields (avoids float error,
--     plenty of range for an academic simulator).
--   * GENERATED BY DEFAULT AS IDENTITY for surrogate keys — allows manual
--     ID assignment in the seed, with sequence reset at the end of the seed.
--   * Plural table names because ORDER is a reserved SQL keyword.
--   * No secondary indexes here — those are added in Layer 4 with benchmarks.
--   * Trade has NO market_id — it was decomposed away (see
--     01_er_and_normalization.md §3.6). The same-market / opposite-side
--     invariant on trades is enforced by a trigger (inter-row rule, not FD).
-- ============================================================================

-- Drop in reverse-dependency order for clean re-runs
DROP TRIGGER  IF EXISTS trades_validate_biz ON trades;
DROP FUNCTION IF EXISTS trg_validate_trade();
DROP TABLE    IF EXISTS withdrawals CASCADE;
DROP TABLE    IF EXISTS deposits    CASCADE;
DROP TABLE    IF EXISTS trades      CASCADE;
DROP TABLE    IF EXISTS orders      CASCADE;
DROP TABLE    IF EXISTS balances    CASCADE;
DROP TABLE    IF EXISTS markets     CASCADE;
DROP TABLE    IF EXISTS assets      CASCADE;
DROP TABLE    IF EXISTS users       CASCADE;


-- ---------------------------------------------------------------------------
-- USERS
-- ---------------------------------------------------------------------------
CREATE TABLE users (
    user_id     BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email       VARCHAR(255) NOT NULL UNIQUE,
    username    VARCHAR(64)  NOT NULL UNIQUE,
    status      VARCHAR(16)  NOT NULL DEFAULT 'ACTIVE'
                  CHECK (status IN ('ACTIVE', 'SUSPENDED', 'CLOSED')),
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now()
);


-- ---------------------------------------------------------------------------
-- ASSETS
-- ---------------------------------------------------------------------------
CREATE TABLE assets (
    asset_id    SMALLINT    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    symbol      VARCHAR(10) NOT NULL UNIQUE,
    name        VARCHAR(64) NOT NULL,
    asset_type  VARCHAR(16) NOT NULL
                  CHECK (asset_type IN ('FIAT', 'CRYPTO')),
    precision   SMALLINT    NOT NULL
                  CHECK (precision BETWEEN 0 AND 18)
);


-- ---------------------------------------------------------------------------
-- MARKETS  (an ordered pair of assets: base / quote)
-- ---------------------------------------------------------------------------
CREATE TABLE markets (
    market_id       INT           GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    base_asset_id   SMALLINT      NOT NULL REFERENCES assets(asset_id),
    quote_asset_id  SMALLINT      NOT NULL REFERENCES assets(asset_id),
    min_order_qty   NUMERIC(20,8) NOT NULL CHECK (min_order_qty > 0),
    status          VARCHAR(16)   NOT NULL DEFAULT 'ACTIVE'
                      CHECK (status IN ('ACTIVE', 'HALTED', 'CLOSED')),
    UNIQUE (base_asset_id, quote_asset_id),
    CHECK  (base_asset_id <> quote_asset_id)
);


-- ---------------------------------------------------------------------------
-- BALANCES  (one row per (user, asset) the user has ever touched)
-- ---------------------------------------------------------------------------
CREATE TABLE balances (
    user_id           BIGINT        NOT NULL REFERENCES users(user_id),
    asset_id          SMALLINT      NOT NULL REFERENCES assets(asset_id),
    available_amount  NUMERIC(20,8) NOT NULL DEFAULT 0
                        CHECK (available_amount >= 0),
    locked_amount     NUMERIC(20,8) NOT NULL DEFAULT 0
                        CHECK (locked_amount >= 0),
    PRIMARY KEY (user_id, asset_id)
);


-- ---------------------------------------------------------------------------
-- ORDERS  (plural because ORDER is a reserved keyword)
-- ---------------------------------------------------------------------------
CREATE TABLE orders (
    order_id         BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id          BIGINT        NOT NULL REFERENCES users(user_id),
    market_id        INT           NOT NULL REFERENCES markets(market_id),
    side             VARCHAR(4)    NOT NULL CHECK (side IN ('BUY', 'SELL')),
    order_type       VARCHAR(8)    NOT NULL DEFAULT 'LIMIT'
                       CHECK (order_type IN ('LIMIT')),
    price            NUMERIC(20,8) NOT NULL CHECK (price > 0),
    quantity         NUMERIC(20,8) NOT NULL CHECK (quantity > 0),
    filled_quantity  NUMERIC(20,8) NOT NULL DEFAULT 0
                       CHECK (filled_quantity >= 0),
    status           VARCHAR(16)   NOT NULL DEFAULT 'OPEN'
                       CHECK (status IN ('OPEN', 'PARTIAL', 'FILLED', 'CANCELLED')),
    created_at       TIMESTAMPTZ   NOT NULL DEFAULT now(),

    -- Invariant: filled cannot exceed total
    CHECK (filled_quantity <= quantity),

    -- Status <-> filled_quantity coherence (CANCELLED is a wildcard because
    -- an order can be cancelled after a partial fill)
    CHECK (
        status = 'CANCELLED'
        OR (status = 'OPEN'    AND filled_quantity = 0)
        OR (status = 'PARTIAL' AND filled_quantity > 0
                               AND filled_quantity < quantity)
        OR (status = 'FILLED'  AND filled_quantity = quantity)
    )
);


-- ---------------------------------------------------------------------------
-- TRADES  (no market_id — see 01_er_and_normalization.md §3.6)
-- ---------------------------------------------------------------------------
CREATE TABLE trades (
    trade_id        BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    maker_order_id  BIGINT        NOT NULL REFERENCES orders(order_id),
    taker_order_id  BIGINT        NOT NULL REFERENCES orders(order_id),
    price           NUMERIC(20,8) NOT NULL CHECK (price > 0),
    quantity        NUMERIC(20,8) NOT NULL CHECK (quantity > 0),
    executed_at     TIMESTAMPTZ   NOT NULL DEFAULT now(),
    CHECK (maker_order_id <> taker_order_id)
);


-- ---------------------------------------------------------------------------
-- Business-rule invariants on trades (not expressible as FDs):
--   (a) maker and taker must be on the same market
--   (b) maker and taker must be on opposite sides (BUY vs SELL)
-- Implemented as a BEFORE INSERT OR UPDATE trigger.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION trg_validate_trade() RETURNS trigger AS $$
DECLARE
    maker_market INT;
    taker_market INT;
    maker_side   TEXT;
    taker_side   TEXT;
BEGIN
    SELECT market_id, side INTO maker_market, maker_side
      FROM orders WHERE order_id = NEW.maker_order_id;

    SELECT market_id, side INTO taker_market, taker_side
      FROM orders WHERE order_id = NEW.taker_order_id;

    IF maker_market IS DISTINCT FROM taker_market THEN
        RAISE EXCEPTION
            'trade rejected: maker market (%) differs from taker market (%)',
            maker_market, taker_market;
    END IF;

    IF maker_side = taker_side THEN
        RAISE EXCEPTION
            'trade rejected: maker and taker are on the same side (%)',
            maker_side;
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trades_validate_biz
BEFORE INSERT OR UPDATE ON trades
FOR EACH ROW EXECUTE FUNCTION trg_validate_trade();


-- ---------------------------------------------------------------------------
-- DEPOSITS  (asset flowing INTO the exchange for a user)
-- ---------------------------------------------------------------------------
CREATE TABLE deposits (
    deposit_id  BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT        NOT NULL REFERENCES users(user_id),
    asset_id    SMALLINT      NOT NULL REFERENCES assets(asset_id),
    amount      NUMERIC(20,8) NOT NULL CHECK (amount > 0),
    status      VARCHAR(16)   NOT NULL DEFAULT 'PENDING'
                  CHECK (status IN ('PENDING', 'COMPLETED', 'FAILED')),
    created_at  TIMESTAMPTZ   NOT NULL DEFAULT now()
);


-- ---------------------------------------------------------------------------
-- WITHDRAWALS  (asset flowing OUT of the exchange for a user)
-- ---------------------------------------------------------------------------
CREATE TABLE withdrawals (
    withdrawal_id  BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id        BIGINT        NOT NULL REFERENCES users(user_id),
    asset_id       SMALLINT      NOT NULL REFERENCES assets(asset_id),
    amount         NUMERIC(20,8) NOT NULL CHECK (amount > 0),
    status         VARCHAR(16)   NOT NULL DEFAULT 'PENDING'
                     CHECK (status IN ('PENDING', 'COMPLETED', 'REJECTED')),
    created_at     TIMESTAMPTZ   NOT NULL DEFAULT now()
);
